# Generated by Django 2.1.15 on 2022-06-25 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nombreCategoria', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Flor',
            fields=[
                ('idFlor', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Flor')),
                ('nombreFlor', models.CharField(max_length=20, verbose_name='Nombre Flor')),
                ('descFlor', models.CharField(max_length=50, verbose_name='Descripción')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Flower.Categoria')),
            ],
        ),
    ]
