# Generated by Django 2.1.15 on 2022-06-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flower', '0002_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
