# Generated by Django 2.1.15 on 2022-06-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flower', '0003_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
