# Generated by Django 2.1.15 on 2022-06-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flower', '0005_auto_20220628_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
