# Generated by Django 4.0.5 on 2022-06-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flower', '0007_auto_20220628_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='flor',
            name='imagen',
            field=models.ImageField(null=True, upload_to='flor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
