# Generated by Django 4.0.5 on 2022-06-28 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flower', '0008_flor_imagen_alter_producto_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flor',
            name='categoria',
        ),
    ]
