# Generated by Django 4.0.5 on 2022-06-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flower', '0009_remove_flor_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='desc',
            field=models.CharField(max_length=80),
        ),
    ]
