# Generated by Django 4.0.5 on 2022-06-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flower', '0010_alter_producto_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flor',
            name='descFlor',
            field=models.CharField(max_length=80, verbose_name='Descripción'),
        ),
    ]
